//! C1 parity gate: `parse` (new, CST-backed) must produce a byte-identical
//! `Program` — and accept/reject identically with the same
//! `CompileErrorKind` — to the frozen pre-C1 `parse_legacy`, across the
//! whole corpus and every parser grammar-test source string.
//!
//! `Program`, `CompileError`, and `CompileErrorKind` all derive
//! `PartialEq`, so `Result<Program, CompileError>` compares directly —
//! the `==` covers every `span`/`line`/`col` field and the error kind.
//!
//! The compiler feeds `parse` a `WithoutComments` token stream; this test
//! lexes the same way, so the CST's trivia fields are empty and the
//! lower-copy is the sole thing under test.

use mtc_post_machine::cst::{BodyKind, Cst, FunctionCst, TopItem, TopKind};
use mtc_post_machine::lexer::{LexMode, TokenKind, lex, lex_with};
use mtc_post_machine::parser::{parse, parse_cst};
use mtc_post_machine::parser_legacy::parse_legacy;

/// The committed corpus: the embedded stdlib, the two goldens, and the
/// lint fixture. Each must parse identically through both paths.
const CORPUS: &[(&str, &str)] = &[
    ("std.pmc", include_str!("../src/stdlib/std.pmc")),
    ("golden/sum.pmc", include_str!("golden/sum.pmc")),
    ("golden/ty.pmc", include_str!("golden/ty.pmc")),
    (
        "lint/unused_labels.pmc",
        include_str!("lint/unused_labels.pmc"),
    ),
];

/// The spec sample from `parser.rs`'s `parses_the_spec_sample` test.
const SPEC_SAMPLE: &str = r#"
// Move right until the first blank cell.
goToEnd() {
1:  right;
    check(1, 2);      // cell marked -> goto 1, blank -> goto 2
2:  left;             // last command - implicit return
}

goToBegin() {
1:  left(2);
2:  check(1, 3);
3:  right(!);
}

main() {
    @goToEnd();
    right;
    check(3, 4);
3:  unmark(!);
4:  mark;
}
"#;

/// Every single-line source string exercised by `parser.rs`'s grammar
/// test suite (`parse_src(...)` / `err_msg(...)`), including the ones
/// generated by `format!`/`for` loops, transcribed verbatim. Both
/// accept and reject cases are here — the parity `==` covers both.
const GRAMMAR_SOURCES: &[&str] = &[
    // comma_groups_parse_and_enforce_positions
    "f() { 1: right, right, mark(5); 5: left, check(1, !); }",
    "f() { left(1), left(2); 1: mark; 2: mark; }",
    "f() { check(1, 2), left; 1: mark; 2: mark; }",
    "f() { halt, left; }",
    "f() { goto 1, left; 1: mark; }",
    "f() { left, goto 1; 1: mark; }",
    // reserved_and_at_rules
    "check() { }",
    "export check() { }",
    "f() { @left(); }",
    "f() { flip; }",
    "f() { goToEnd(); }",
    // empty_builtin_parens_are_a_syntax_error (format! expansion + ok cases)
    "f() { left(); }",
    "f() { right(); }",
    "f() { mark(); }",
    "f() { unmark(); }",
    "f() { left; }",
    "f() { left(5); }",
    "f() { left(!); }",
    "f() { @f(); }",
    // goto_bang_is_a_dedicated_error
    "f() { goto !; }",
    // duplicate_and_dangling_diagnostics
    "f() { } f() { }",
    "f() { 1: left; 1: right; }",
    "f() { left; 2: }",
    // empty_function_and_stacked_labels
    "f() { }",
    "f() { 1: 2: left; }",
    // unicode_function_names_and_calls
    "идиВКонец() { right(!); } main() { @идиВКонец(); }",
    // export_is_contextual_and_main_auto_exports
    "export api() { left; } helper() { right; } main() { mark; }",
    "export() { left; } main() { @export(); }",
    // nested_definitions_parse_recursively
    "main() { walk() { step() { right; } @step(); } @walk(); }",
    // namespace_blocks_stamp_paths_and_nest
    "namespace a { f() { left; } namespace b { g() { right; } } } h() { mark; }",
    "namespace() { left; } main() { @namespace(); }",
    // import_paths_aliases_and_scopes_parse
    "use a, std::b as c; namespace ns { use d::e; }",
    // qualified_calls_parse_to_joined_names
    "main() { @std::api::run(); }",
    "main() { @std::(); }",
    // namespace_name_pool_and_reopening_rules
    "namespace a { f() { left; } } namespace a { g() { right; } }",
    "namespace a { f() { left; } } namespace a { f() { right; } }",
    "namespace a { f() { left; } } namespace b { f() { right; } }",
    "namespace a { } a() { left; }",
    "a() { left; } namespace a { }",
    "namespace a { f() { left; }",
    // use_stays_illegal_inside_function_bodies
    "main() { use go; }",
    // nested_export_and_same_scope_duplicates_error
    "main() { export inner() { left; } }",
    "main() { f() { left; } f() { right; } }",
    // spans_are_retained_for_labels_names_and_items
    "f() {\n  5 : right(7);\n7:  left;\n}",
    // call_and_check_spans
    "f() { @a::b(); check(1, !); 1: left; }",
    // import_spans_exclude_the_alias
    "use std::go as g;\nmain() { @g(); }",
    // reserved_words_are_barred_in_every_path_segment
    "main() { @std::goto(); }",
    "use std::goto;\nmain() { right; }",
    // keyword_followed_by_brace_gets_a_hint
    "namespace {\n}",
    "use {}",
    "export {}",
    // use_and_namespace_inside_a_body_say_the_real_rule
    "main() { use go; }",
    "main() { namespace x; }",
    // single_colon_in_a_path_hints_double_colon
    "use std:b;\nmain() { right; }",
    "main() { @f:g(); }",
    // namespace_naming_errors_say_namespace
    "namespace goto { }",
    "namespace a { } a() { right; }",
    // unclosed_function_body_mentions_the_brace
    "f() { left;",
    // top_level_statements_state_the_rule
    "left;\nmain() { right; }",
    "goto 1;",
    "@foo();",
    // spaced_label_colons_and_paths_stay_legal
    "main() { 1 : right; }",
    "main() { 1: 2: right; }",
    "use std :: goToEnd;\nmain() { @goToEnd(); }",
    // empty_builtin_parens_message_names_the_builtin_and_the_fix
    "main() { mark(); }",
    "f() { } main() { @f(); }",
];

/// The single assertion that carries the whole gate: identical `Result`
/// (Ok `Program` or Err with the same span + kind) from both paths.
fn assert_parity(label: &str, src: &str) {
    let tokens = lex(src).expect("corpus/grammar source must lex");
    let new = parse(&tokens);
    let old = parse_legacy(&tokens);
    assert_eq!(
        new.is_ok(),
        old.is_ok(),
        "{label}: accept/reject disagree — new={new:?} old={old:?}"
    );
    assert_eq!(new, old, "{label}: parse output differs from parse_legacy");
}

#[test]
fn corpus_parses_identically_through_both_paths() {
    for (label, src) in CORPUS {
        assert_parity(label, src);
        // The corpus is real programs — both paths must accept.
        assert!(
            parse(&lex(src).unwrap()).is_ok(),
            "{label}: expected the corpus to parse"
        );
    }
}

#[test]
fn spec_sample_parses_identically() {
    assert_parity("spec_sample", SPEC_SAMPLE);
}

#[test]
fn grammar_suite_sources_parse_identically() {
    for src in GRAMMAR_SOURCES {
        assert_parity(src, src);
    }
}

/// Every comment token placed somewhere in the CST — the Task-3 "nothing
/// dropped" contract. Counts comment nodes across the whole tree (own-line
/// `Comment` items + `trailing` on imports/statements + per-comma-item
/// `leading`) and asserts it equals the number of `Comment` tokens in the
/// `WithComments` stream. Recursion covers nested functions + namespaces.
fn count_body(f: &FunctionCst) -> usize {
    let mut n = 0;
    for bi in &f.body {
        match &bi.kind {
            BodyKind::Comment(_) => n += 1,
            BodyKind::Statement(s) => {
                n += usize::from(s.trailing.is_some());
                n += s.items.iter().map(|ci| ci.leading.len()).sum::<usize>();
            }
            BodyKind::Nested(g) => n += count_body(g),
        }
    }
    n
}

fn count_top(items: &[TopItem]) -> usize {
    let mut n = 0;
    for item in items {
        match &item.kind {
            TopKind::Comment(_) => n += 1,
            TopKind::Import(imp) => n += usize::from(imp.trailing.is_some()),
            TopKind::Namespace(nsc) => n += count_top(&nsc.items),
            TopKind::Function(f) => n += count_body(f),
        }
    }
    n
}

fn count_cst_comments(cst: &Cst) -> usize {
    count_top(&cst.items)
}

#[test]
fn with_comments_parse_drops_no_comment_across_the_corpus() {
    let mut sources: Vec<(&str, &str)> = CORPUS.to_vec();
    sources.push(("spec_sample", SPEC_SAMPLE));
    for (label, src) in sources {
        let tokens = lex_with(src, LexMode::WithComments).unwrap();
        let token_comments = tokens
            .iter()
            .filter(|t| matches!(t.kind, TokenKind::Comment(_)))
            .count();
        let cst = parse_cst(&tokens).expect("corpus must parse WithComments too");
        let cst_comments = count_cst_comments(&cst);
        assert_eq!(
            cst_comments, token_comments,
            "{label}: {cst_comments} CST comment nodes != {token_comments} comment tokens \
             (a comment was dropped or double-counted)"
        );
    }
    // Grammar sources that parse carry no comments — assert parse_cst
    // invents none from a WithComments stream either.
    for src in GRAMMAR_SOURCES {
        let tokens = lex_with(src, LexMode::WithComments).unwrap();
        if let Ok(cst) = parse_cst(&tokens) {
            assert_eq!(count_cst_comments(&cst), 0, "{src}: comment invented");
        }
    }
}
