//! Renders a fish completion script from the registry
//! (`completions::registry`). A pure text transform, like `zsh.rs` and
//! `bash.rs`: it knows nothing about TM-1 itself, so a new subcommand or
//! flag reaches the script by being registered, never by being
//! special-cased here.
//!
//! fish completions are declarative — one `complete -c tmt …` statement
//! per candidate, each guarded by a `-n` condition that says when it
//! applies — so unlike the bash script there is no function to run:
//! fish evaluates the conditions itself. What each registry shape
//! becomes:
//!
//! * the root's subcommand names are offered under `__fish_use_subcommand`,
//!   each with its gloss; a group's actions under "the group is on the
//!   line and none of its actions is yet"; a leaf's flags under "the
//!   subcommand (and, for a group's action, the action) is on the line";
//! * a flag's spelling decides its option kind: `--name` is `-l name`, a
//!   one-letter `-x` is `-s x`, and a longer single-dash flag such as
//!   `-O0` or `-Werror` is an old-style `-o O0` option;
//! * a `Value` flag carries its value shape — `-x -a 'choices'` for a
//!   closed set, `-r -F` for any file, `-r -f -a '(__fish_complete_suffix
//!   .ext)'` per registered extension, `-x -a '(__fish_complete_directories)'`
//!   for a directory, bare `-x` for free text;
//! * an `OptionalEqualsValue` flag is the bare option plus the
//!   `name=choice` tokens, the latter offered only once the current
//!   token already starts with `name=` — never a space-separated value,
//!   which the parser would not read;
//! * a `SuffixFamily` is one long option per choice;
//! * fish offers an option again however often it is already on the
//!   line, so every non-repeatable boolean flag (family members included)
//!   carries `and not __fish_seen_argument <itself>`; a value flag does
//!   not, since its entry is also what tells fish the option takes an
//!   argument, and hiding it would make the value complete as a file. An
//!   exclusive group adds the same guard for each group-mate, so a flag
//!   disappears once a mate is on the line;
//! * a file positional offers `__fish_complete_suffix` per extension.
//!   That helper is fish's own convention: files with the extension come
//!   first and every other file follows them, so it ranks rather than
//!   filters (bash's script filters). It includes directories, so
//!   `FileHint::dirs` needs no separate rendering. `build`'s positional
//!   adds the manifest's target names by shelling out to `tmt build
//!   --list-targets` at completion time (docs/tmt/cli.md (tmt build)).
//!
//! `FlagSpec::requires` is not rendered, matching the zsh renderer.

use super::registry::{
    CommandSpec, FileHint, FlagKind, Positional, PositionalHint, Registry, ValueHint, child_help,
    expand,
};

pub fn render(registry: &Registry) -> String {
    let root = registry
        .commands
        .iter()
        .find(|c| c.path.is_empty())
        .expect("registry always has a root entry");
    let mut groups: Vec<&str> = Vec::new();
    for command in registry.commands.iter().filter(|c| c.path.len() == 2) {
        let name = command.path[0].as_str();
        if !groups.contains(&name) {
            groups.push(name);
        }
    }

    let mut out = String::new();
    out.push_str(
        "# fish completion for tmt — generated by `tmt completions fish` from the CLI\n\
         # registry; do not hand-edit, regenerate with `tmt completions fish`.\n\n\
         # Positional arguments never default to file names; each subcommand below\n\
         # declares what its own positional accepts.\n\
         complete -c tmt -f\n\n",
    );

    // Root: global flags and the subcommand names.
    out.push_str("# tmt\n");
    for flag in &root.flags {
        for token in expand(flag) {
            out.push_str(&format!(
                "complete -c tmt -n '__fish_use_subcommand' {} -d '{}'\n",
                option(&token),
                esc(&flag.help)
            ));
        }
    }
    let Positional::One(PositionalHint::Choices(choices)) = &root.positional else {
        panic!("root positional must be a subcommand-name choice list");
    };
    for choice in choices {
        out.push_str(&format!(
            "complete -c tmt -n '__fish_use_subcommand' -a {} -d '{}'\n",
            choice.value,
            esc(&choice.help)
        ));
    }
    out.push('\n');

    for leaf in registry.commands.iter().filter(|c| c.path.len() == 1) {
        let seen = format!("__fish_seen_subcommand_from {}", leaf.path[0]);
        render_leaf(&mut out, leaf, &seen);
    }

    for group in &groups {
        let children: Vec<&CommandSpec> = registry
            .commands
            .iter()
            .filter(|c| c.path.len() == 2 && c.path[0] == *group)
            .collect();
        let names: Vec<&str> = children.iter().map(|c| c.path[1].as_str()).collect();
        out.push_str(&format!("# tmt {group}\n"));
        for child in &children {
            out.push_str(&format!(
                "complete -c tmt -n '__fish_seen_subcommand_from {group}; and not __fish_seen_subcommand_from {}' -f -a {} -d '{}'\n",
                names.join(" "),
                child.path[1],
                esc(child_help(child))
            ));
        }
        out.push('\n');
        for child in &children {
            let seen = format!(
                "__fish_seen_subcommand_from {group}; and __fish_seen_subcommand_from {}",
                child.path[1]
            );
            render_leaf(&mut out, child, &seen);
        }
    }
    out
}

fn render_leaf(out: &mut String, spec: &CommandSpec, seen: &str) {
    out.push_str(&format!("# tmt {}\n", spec.path.join(" ")));
    for flag in &spec.flags {
        let mut condition = seen.to_string();
        // fish offers an option again however many times it is already on
        // the line, so a non-repeatable flag guards against itself (a
        // family member is its own option and gets its own guard below).
        // Not a value flag, though: its entry is also what tells fish the
        // option takes an argument, and a guard that hides the entry once
        // `--lang` is on the line would leave `--lang p` completing as a
        // file name instead of a language.
        if !flag.repeatable
            && matches!(
                flag.kind,
                FlagKind::Boolean | FlagKind::OptionalEqualsValue(_)
            )
        {
            condition.push_str(&format!(
                "; and not __fish_seen_argument {}",
                option(&flag.name)
            ));
        }
        if let Some(group) = &flag.exclusive_group {
            for mate in spec
                .flags
                .iter()
                .filter(|f| f.name != flag.name && f.exclusive_group.as_deref() == Some(group))
            {
                condition.push_str(&format!(
                    "; and not __fish_seen_argument {}",
                    option(&mate.name)
                ));
            }
        }
        let desc = esc(&flag.help);
        match &flag.kind {
            FlagKind::Boolean => out.push_str(&format!(
                "complete -c tmt -n '{condition}' {} -d '{desc}'\n",
                option(&flag.name)
            )),
            FlagKind::Value(hint) => out.push_str(&format!(
                "complete -c tmt -n '{condition}' {} {} -d '{desc}'\n",
                option(&flag.name),
                value_shape(hint)
            )),
            FlagKind::OptionalEqualsValue(hint) => {
                out.push_str(&format!(
                    "complete -c tmt -n '{condition}' {} -d '{desc}'\n",
                    option(&flag.name)
                ));
                if let ValueHint::Choices(choices) = hint {
                    let tokens: Vec<String> = choices
                        .iter()
                        .map(|c| format!("{}={c}", flag.name))
                        .collect();
                    out.push_str(&format!(
                        "complete -c tmt -n '{condition}; and string match -q -- \\'{}=*\\' (commandline -ct)' -f -a '{}' -d '{desc}'\n",
                        flag.name,
                        tokens.join(" ")
                    ));
                }
            }
            FlagKind::SuffixFamily(_) => {
                for token in expand(flag) {
                    out.push_str(&format!(
                        "complete -c tmt -n '{condition}; and not __fish_seen_argument {}' {} -d '{desc}'\n",
                        option(&token),
                        option(&token)
                    ));
                }
            }
        }
    }
    match &spec.positional {
        Positional::None => {}
        Positional::One(hint) | Positional::OneOrMore(hint) => match hint {
            PositionalHint::File(file) => {
                for entry in suffix_completions(file) {
                    out.push_str(&format!("complete -c tmt -n '{seen}' -f -a '{entry}'\n"));
                }
            }
            PositionalHint::FilesOrTargets(file) => {
                for entry in suffix_completions(file) {
                    out.push_str(&format!("complete -c tmt -n '{seen}' -f -a '{entry}'\n"));
                }
                out.push_str(&format!(
                    "complete -c tmt -n '{seen}' -f -a '(tmt build --list-targets 2>/dev/null | string replace -r \\'\\\\t.*\\' \\'\\')'\n"
                ));
            }
            PositionalHint::Choices(choices) => {
                for choice in choices {
                    out.push_str(&format!(
                        "complete -c tmt -n '{seen}' -f -a {} -d '{}'\n",
                        choice.value,
                        esc(&choice.help)
                    ));
                }
            }
            PositionalHint::Text => {}
        },
    }
    out.push('\n');
}

/// The `complete` option switch for a flag token: `--name` → `-l name`,
/// a one-letter `-x` → `-s x`, anything longer with one dash → `-o name`
/// (fish's "old-style" single-dash long option).
fn option(token: &str) -> String {
    if let Some(long) = token.strip_prefix("--") {
        format!("-l {long}")
    } else {
        let short = token.strip_prefix('-').unwrap_or(token);
        if short.len() == 1 {
            format!("-s {short}")
        } else {
            format!("-o {short}")
        }
    }
}

/// The argument shape switches for a `Value` flag.
fn value_shape(hint: &ValueHint) -> String {
    match hint {
        ValueHint::Text => "-x".to_string(),
        ValueHint::Choices(choices) => format!("-x -a '{}'", choices.join(" ")),
        ValueHint::File(file) => {
            if file.extensions.is_empty() {
                "-r -F".to_string()
            } else {
                // One `-a` per extension would need one `complete` line
                // each; a single line takes them as one argument list of
                // command substitutions instead (fish expands `-a`'s
                // string like a command line, so each substitution
                // contributes its lines to one candidate list).
                let calls: Vec<String> = suffix_completions(file);
                format!("-r -f -a '{}'", calls.join(" "))
            }
        }
        ValueHint::Directory => "-x -a '(__fish_complete_directories)'".to_string(),
    }
}

/// One `(__fish_complete_suffix .ext)` substitution per registered
/// extension (the helper offers directories alongside, so a `dirs` hint
/// needs nothing extra).
fn suffix_completions(hint: &FileHint) -> Vec<String> {
    hint.extensions
        .iter()
        .map(|ext| format!("(__fish_complete_suffix .{ext})"))
        .collect()
}

/// Escape for the inside of a fish single-quoted string: only `\` and
/// `'` are special there.
fn esc(text: &str) -> String {
    text.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::completions::registry::registry;

    fn script() -> String {
        render(&registry())
    }

    fn line_with(s: &str, needle: &str) -> String {
        s.lines()
            .find(|l| l.contains(needle))
            .unwrap_or_else(|| panic!("no line contains {needle:?}:\n{s}"))
            .to_string()
    }

    #[test]
    fn disables_file_completion_globally_then_declares_subcommands() {
        let s = script();
        assert!(s.starts_with("# fish completion for tmt"), "{s}");
        assert!(s.contains("\ncomplete -c tmt -f\n"), "{s}");
        assert_eq!(
            line_with(&s, "-a compile "),
            "complete -c tmt -n '__fish_use_subcommand' -a compile -d '.tmc source -> .tmo object (-S for .tma, --emit-ir for world IR JSON)'"
        );
        assert!(
            s.contains("-n '__fish_use_subcommand' -l version -d"),
            "{s}"
        );
    }

    #[test]
    fn flags_are_classified_as_long_short_or_old_style() {
        let s = script();
        assert_eq!(
            line_with(&s, "-l strip-debugger -d"),
            "complete -c tmt -n '__fish_seen_subcommand_from compile; and not __fish_seen_argument -l strip-debugger' -l strip-debugger -d 'drop `brk` at codegen'"
        );
        assert!(
            s.contains("; and not __fish_seen_argument -s g' -s g -d"),
            "{s}"
        );
        assert!(
            s.contains("; and not __fish_seen_argument -o Werror' -o Werror -d"),
            "{s}"
        );
    }

    #[test]
    fn a_used_flag_is_withheld_unless_repeatable() {
        let s = script();
        // fish never withholds a used option by itself: every non-repeatable
        // flag guards against itself, family members included …
        assert!(
            s.contains("; and not __fish_seen_argument -l fno-inline' -l fno-inline -d"),
            "{s}"
        );
        // … while a repeatable flag stays on offer.
        assert!(
            s.contains("complete -c tmt -n '__fish_seen_subcommand_from link' -s L -x -a"),
            "{s}"
        );
    }

    #[test]
    fn exclusive_flags_are_withheld_once_a_group_mate_is_present() {
        let s = script();
        assert_eq!(
            line_with(&s, "-o O0 -d 'optimization level O0 (default)'"),
            "complete -c tmt -n '__fish_seen_subcommand_from compile; and not __fish_seen_argument -o O0; and not __fish_seen_argument -o O1' -o O0 -d 'optimization level O0 (default)'"
        );
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from build; and not __fish_seen_argument -l debug; and not __fish_seen_argument -l release' -l debug"
            ),
            "{s}"
        );
    }

    #[test]
    fn fno_expands_to_one_long_option_per_pass() {
        let s = script();
        for pass in crate::optimizer::pass_names() {
            assert!(
                s.contains(&format!(" -l fno-{pass} -d")),
                "--fno-{pass}:\n{s}"
            );
        }
    }

    #[test]
    fn emit_ir_is_bare_or_equals_joined_only() {
        let s = script();
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from compile; and not __fish_seen_argument -l emit-ir' -l emit-ir -d"
            ),
            "{s}"
        );
        let joined = line_with(&s, "-a '--emit-ir=lowered --emit-ir=final");
        assert!(
            joined.contains("string match -q -- \\'--emit-ir=*\\' (commandline -ct)"),
            "joined tokens are offered only once the head is typed:\n{joined}"
        );
        assert!(joined.contains("--emit-ir=after:inline"), "{joined}");
        assert!(
            !s.contains("-l emit-ir -r"),
            "never a space-separated stage:\n{s}"
        );
    }

    #[test]
    fn value_flags_carry_their_value_shapes() {
        let s = script();
        assert!(
            s.contains(" -l call-mech -x -a 'mono frames hybrid' -d"),
            "{s}"
        );
        assert!(
            s.contains(" -s L -x -a '(__fish_complete_directories)' -d"),
            "{s}"
        );
        // A value flag carries no self-guard (see the module doc).
        assert!(
            s.contains("-n '__fish_seen_subcommand_from compile' -s o -r -F -d"),
            "{s}"
        );
        assert!(
            s.contains(" -l map -r -f -a '(__fish_complete_suffix .tmx.map)' -d"),
            "{s}"
        );
        assert!(s.contains(" -l entry -x -d"), "{s}");
        // Several extensions become one argument list of substitutions.
        assert!(
            s.contains(
                " -l from -r -f -a '(__fish_complete_suffix .tmx) (__fish_complete_suffix .tmc)' -d"
            ),
            "{s}"
        );
    }

    #[test]
    fn positionals_are_extension_filtered_and_build_adds_targets() {
        let s = script();
        assert!(
            s.contains(
                "complete -c tmt -n '__fish_seen_subcommand_from compile' -f -a '(__fish_complete_suffix .tmc)'\n"
            ),
            "{s}"
        );
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from lint' -f -a '(__fish_complete_suffix .tma)'"
            ),
            "{s}"
        );
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from build' -f -a '(tmt build --list-targets 2>/dev/null | string replace -r \\'\\\\t.*\\' \\'\\')'"
            ),
            "{s}"
        );
        // A choice positional lists each word with its gloss.
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from completions' -f -a zsh -d 'Z shell completion script'"
            ),
            "{s}"
        );
    }

    #[test]
    fn groups_offer_actions_then_the_action_flags() {
        let s = script();
        assert_eq!(
            line_with(&s, "-a new -d"),
            "complete -c tmt -n '__fish_seen_subcommand_from tape-block; and not __fish_seen_subcommand_from new set show' -f -a new -d 'write a blank .tmt template sized to an executable'"
        );
        // The action's flags are guarded by the action, and `--in-place`
        // additionally by itself and by its `-o` group-mate.
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from tape-block; and __fish_seen_subcommand_from set; and not __fish_seen_argument -l in-place; and not __fish_seen_argument -s o' -l in-place"
            ),
            "{s}"
        );
    }

    /// One thing the script offers: a flag token, a bare word (a
    /// subcommand, a group's action, a choice positional, an
    /// `--emit-ir=`-joined token), or a closed value choice of a flag —
    /// each keyed by the command path whose condition guards it.
    #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
    enum Offer {
        Flag(Vec<String>, String),
        Word(Vec<String>, String),
        Value(Vec<String>, String, String),
    }

    /// Splits one `complete` line into shell words: fish single quotes,
    /// inside which only `\'` and `\\` are escapes.
    fn words(line: &str) -> Vec<String> {
        let mut out = Vec::new();
        let mut current = String::new();
        let mut in_word = false;
        let mut chars = line.chars();
        while let Some(c) = chars.next() {
            match c {
                '\'' => {
                    in_word = true;
                    while let Some(q) = chars.next() {
                        match q {
                            '\'' => break,
                            '\\' => match chars.next() {
                                Some(e @ ('\'' | '\\')) => current.push(e),
                                Some(e) => {
                                    current.push('\\');
                                    current.push(e);
                                }
                                None => current.push('\\'),
                            },
                            other => current.push(other),
                        }
                    }
                }
                ' ' => {
                    if in_word {
                        out.push(std::mem::take(&mut current));
                        in_word = false;
                    }
                }
                other => {
                    in_word = true;
                    current.push(other);
                }
            }
        }
        if in_word {
            out.push(current);
        }
        out
    }

    /// The command path a `-n` condition guards: `__fish_use_subcommand`
    /// is the root, otherwise every POSITIVE `__fish_seen_subcommand_from`
    /// clause contributes its word.
    fn condition_path(condition: &str) -> Vec<String> {
        if condition == "__fish_use_subcommand" {
            return Vec::new();
        }
        condition
            .split("; and ")
            .filter_map(|clause| clause.strip_prefix("__fish_seen_subcommand_from "))
            .map(str::to_string)
            .collect()
    }

    /// The fish option switch back to the flag token it spells.
    fn token_of(switch: &str, name: &str) -> String {
        match switch {
            "-l" => format!("--{name}"),
            _ => format!("-{name}"),
        }
    }

    /// Everything the rendered script offers, read back out of it.
    fn offers_in(script: &str) -> std::collections::BTreeSet<Offer> {
        let mut out = std::collections::BTreeSet::new();
        for line in script.lines().filter(|l| l.starts_with("complete ")) {
            let w = words(line);
            let Some(n) = w.iter().position(|x| x == "-n") else {
                continue; // the global `complete -c tmt -f`
            };
            let path = condition_path(&w[n + 1]);
            let mut flag = None;
            let mut listed = Vec::new();
            let mut i = n + 2;
            while i < w.len() {
                match w[i].as_str() {
                    s @ ("-l" | "-s" | "-o") => {
                        flag = Some(token_of(s, &w[i + 1]));
                        i += 2;
                    }
                    "-a" => {
                        if !w[i + 1].starts_with('(') {
                            listed.extend(w[i + 1].split_whitespace().map(str::to_string));
                        }
                        i += 2;
                    }
                    "-d" => i += 2,
                    _ => i += 1,
                }
            }
            match flag {
                Some(token) => {
                    for value in listed {
                        out.insert(Offer::Value(path.clone(), token.clone(), value));
                    }
                    out.insert(Offer::Flag(path, token));
                }
                None => {
                    for word in listed {
                        out.insert(Offer::Word(path.clone(), word));
                    }
                }
            }
        }
        out
    }

    /// Everything the registry says the script must offer.
    fn offers_in_registry(reg: &Registry) -> std::collections::BTreeSet<Offer> {
        let mut out = std::collections::BTreeSet::new();
        for command in &reg.commands {
            let path = command.path.clone();
            if path.len() == 2 {
                out.insert(Offer::Word(vec![path[0].clone()], path[1].clone()));
            }
            for flag in &command.flags {
                for token in expand(flag) {
                    out.insert(Offer::Flag(path.clone(), token));
                }
                match &flag.kind {
                    FlagKind::Value(ValueHint::Choices(choices)) => {
                        for c in choices {
                            out.insert(Offer::Value(path.clone(), flag.name.clone(), c.clone()));
                        }
                    }
                    FlagKind::OptionalEqualsValue(ValueHint::Choices(choices)) => {
                        for c in choices {
                            out.insert(Offer::Word(path.clone(), format!("{}={c}", flag.name)));
                        }
                    }
                    _ => {}
                }
            }
            if let Positional::One(PositionalHint::Choices(choices))
            | Positional::OneOrMore(PositionalHint::Choices(choices)) = &command.positional
            {
                for c in choices {
                    out.insert(Offer::Word(path.clone(), c.value.clone()));
                }
            }
        }
        out
    }

    /// The registry-wide guard: every subcommand, group action, flag
    /// token (suffix-family members included), closed value choice and
    /// choice positional the registry declares is offered by the script
    /// under its own command's condition, and the script offers nothing
    /// else. A set-compare in both directions, so a registry entry the
    /// renderer drops and an offer the registry never declared both
    /// redden it. Red if `render_leaf` skips any one flag (e.g. a
    /// `filter(|f| f.name != "--strip-debugger")` on its flag loop), or
    /// if the group-action loop is removed.
    #[test]
    fn the_script_offers_exactly_what_the_registry_declares() {
        let reg = registry();
        let script = render(&reg);
        let got = offers_in(&script);
        let want = offers_in_registry(&reg);
        let missing: Vec<&Offer> = want.difference(&got).collect();
        let extra: Vec<&Offer> = got.difference(&want).collect();
        assert!(
            missing.is_empty() && extra.is_empty(),
            "fish script drifted from the registry\nmissing: {missing:#?}\nextra: {extra:#?}"
        );
        // The guard reads a non-trivial script: every command is covered.
        assert!(want.len() > reg.commands.len(), "{want:#?}");
    }

    #[test]
    fn an_apostrophe_in_a_description_is_escaped() {
        let s = script();
        assert!(
            s.contains("-d 'repin a tape\\'s glyphs (KEY=GLYPHS)'"),
            "{s}"
        );
    }
}
