//! Shell completion for `tmt`. `tmt` is hand-rolled (no clap —
//! deliberately, per the workspace's minimal-dependency policy), so a
//! completion script can't be generated by a framework the way a
//! clap-based CLI gets one for free. Instead, [`registry::registry`] is
//! the single in-crate description of the CLI surface (subcommands,
//! flags, positional file-extension filters), and each shell renderer is
//! a pure text transform over it. Library code here never prints —
//! `cli::completions` calls the renderer and hands the string back for
//! `bin/tmt.rs` to print, per the thin-renderer rule.
//!
//! The registry can drift from the real parser if a flag is added to
//! `cli/build.rs` / `cli/inspect.rs` / `cli/run.rs` / `cli/lint.rs` /
//! `cli/fmt.rs` without a matching registry update — nothing in the type
//! system prevents that for a hand-rolled parser.
//! `crates/turing-machine/tests/completions_registry.rs` is the drift
//! guard: it probes the actual parser with every registry entry, and
//! cross-checks the `--fno-<pass>` / `--emit-ir=after:<pass>` choices
//! against the optimizer's own pass-name list rather than a retyped copy.

pub mod registry;
