//! Shell completion for `tmt`. `tmt` is hand-rolled (no clap —
//! deliberately, per the workspace's minimal-dependency policy), so a
//! completion script can't be generated by a framework the way a
//! clap-based CLI gets one for free. Instead, [`registry::registry`] is
//! the single in-crate description of the CLI surface (subcommands,
//! flags, positional file-extension filters), and each shell renderer is
//! a pure text transform over it. Library code here never prints —
//! `cli::completions` calls the renderer and hands the string back for
//! `bin/tmt.rs` to print, per the thin-renderer rule.
//!
//! The registry can drift from the real parser if a flag is added to
//! `cli/build.rs` / `cli/inspect.rs` / `cli/run.rs` / `cli/lint.rs` /
//! `cli/fmt.rs` without a matching registry update — nothing in the type
//! system prevents that for a hand-rolled parser.
//! `crates/turing-machine/tests/completions_registry.rs` is the drift
//! guard: it probes the actual parser with every registry entry, and
//! cross-checks the `--fno-<pass>` / `--emit-ir=after:<pass>` choices
//! against the optimizer's own pass-name list rather than a retyped copy.

mod bash;
mod fish;
pub mod registry;
mod zsh;

/// A shell `tmt completions` can target. Each has its own renderer over
/// the one registry (`zsh.rs`, `bash.rs`, `fish.rs`); zsh shipped first
/// and proved the registry, bash and fish followed. This mirrors the
/// PM-1 `pmt` precedent exactly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shell {
    Zsh,
    Bash,
    Fish,
}

pub fn parse_shell(name: &str) -> Result<Shell, String> {
    match name {
        "zsh" => Ok(Shell::Zsh),
        "bash" => Ok(Shell::Bash),
        "fish" => Ok(Shell::Fish),
        other => Err(format!(
            "unknown shell `{other}` (want one of: zsh, bash, fish)"
        )),
    }
}

/// Render the completion script for `shell`, or an error naming it as a
/// recognized-but-not-yet-implemented follow-on.
pub fn render(shell: Shell) -> Result<String, String> {
    match shell {
        Shell::Zsh => Ok(zsh::render(&registry::registry())),
        Shell::Bash => Ok(bash::render(&registry::registry())),
        Shell::Fish => Ok(fish::render(&registry::registry())),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_shell_name_is_recognized_and_renders() {
        for name in ["zsh", "bash", "fish"] {
            let shell = parse_shell(name).expect("recognized shell name");
            let script = render(shell).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert!(
                script.contains(&format!("tmt completions {name}")),
                "{name}: the script names how to regenerate itself"
            );
        }
        let unknown = parse_shell("nushell").expect_err("unknown shell name");
        assert!(unknown.contains("unknown shell"), "{unknown}");
    }
}
