//! Pins `std.tmh` — the embedded standard library's own committed header,
//! generated by `tmt interface` over `std.tmc` and never hand-edited
//! (docs/tmt/stdlib.md (the shipped header)) — and the contract agreement
//! `stdlib::header()`'s re-point depends on (docs/tmt/language.md
//! (declarations)): `resolved()` is the analysis of `std.tmc` itself,
//! bodies and all; `header()` is the analysis of its declarations, and
//! the two must agree on every exported routine's `writes` contract,
//! since that is all the footprint inference ever reads off an external
//! module.

use std::collections::BTreeMap;
use std::sync::atomic::{AtomicU64, Ordering};

use mtc_turing_machine::cli::execute;
use mtc_turing_machine::stdlib;

fn args(list: &[&str]) -> Vec<String> {
    list.iter().map(|s| s.to_string()).collect()
}

/// A fresh, per-call fixture directory under `CARGO_TARGET_TMPDIR`, named
/// uniquely by process id + an atomic counter — copied verbatim from
/// `tests/mode_equivalence.rs::scratch` (docs/superpowers plan's "temp
/// paths in tests" rule).
fn scratch(name: &str) -> std::path::PathBuf {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    let dir = std::path::PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("{name}-{}-{n}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

/// The "generated, do not edit" notice `std.tmh` carries, in the style of
/// a golden's own regen convention. `tmt interface` itself stays
/// comment-free for ordinary user files (docs/tmt/cli.md (interface),
/// `crate::header`'s own module doc) — the printer never emits this text.
/// It is added ONLY here, by the one generator path both the byte pin and
/// `regen` call, so the pin stays a plain byte compare against exactly
/// what `regen` would (re)write, and the printer's own output — what
/// every OTHER `tmt interface` caller sees — never carries it.
const GENERATED_NOTICE: &str = "\
// GENERATED — do not edit by hand.
//
// Derived from `std.tmc` by `tmt interface` (docs/tmt/stdlib.md (the
// shipped header)). Regenerate with the `#[ignore]`d `regen` test in
// `stdlib_header.rs`; a hand edit is overwritten on the next regen and
// caught meanwhile by `std_tmh_is_what_tmt_interface_prints`.

";

/// Runs `tmt interface` over [`stdlib::SOURCE`] through the public CLI
/// (the printer itself is crate-private) and prepends [`GENERATED_NOTICE`]
/// — the ONE generator both the byte pin and `regen` call.
fn generate_std_tmh() -> String {
    let dir = scratch("stdlib_header_generate");
    let path = dir.join("std.tmc");
    std::fs::write(&path, stdlib::SOURCE).unwrap();
    let out = execute(&args(&["interface", path.to_str().unwrap()]))
        .unwrap_or_else(|e| panic!("interface std.tmc: {e}"));
    assert_eq!(out.code, 0, "{}", out.stderr);
    format!("{GENERATED_NOTICE}{}", out.stdout)
}

/// The committed `std.tmh`'s own path on disk, for `regen` to write to.
fn std_tmh_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/stdlib/std.tmh")
}

/// Extract `qualified::routine::name -> "export routine …;"` from one
/// rendered header — the SAME small brace-depth walk
/// `header_roundtrip.rs`'s own `qualified_routines` uses (CLAUDE.md
/// (testing conventions): no shared test-support module, each file
/// defines its own local helpers). Good enough for text this printer
/// itself produced (or, here, the committed file derived from it); not a
/// general `.tmc` parser. A `use` line or the leading generated-notice
/// comment matches none of the four patterns below, so both are silently
/// skipped, exactly like any other non-matching line.
fn qualified_routines(header: &str) -> BTreeMap<String, String> {
    let mut stack: Vec<Option<String>> = Vec::new();
    let mut out = BTreeMap::new();
    for raw in header.lines() {
        let trimmed = raw.trim();
        if trimmed.is_empty() {
            continue;
        }
        if let Some(name) = trimmed
            .strip_prefix("namespace ")
            .and_then(|s| s.strip_suffix(" {"))
        {
            stack.push(Some(name.to_string()));
            continue;
        }
        if trimmed == "}" {
            stack.pop();
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("export routine ") {
            let name = rest.split('(').next().unwrap_or(rest);
            let ns: Vec<&str> = stack.iter().filter_map(|s| s.as_deref()).collect();
            let qualified = if ns.is_empty() {
                name.to_string()
            } else {
                format!("{}::{name}", ns.join("::"))
            };
            out.insert(qualified, trimmed.to_string());
            continue;
        }
        if trimmed.ends_with('{') {
            stack.push(None);
        }
    }
    out
}

/// The write-set suffix of a rendered signature line — from the `writes`
/// keyword to the end. Copied from `header_roundtrip.rs`'s own helper.
fn write_set_suffix(line: &str) -> &str {
    line.find("writes").map(|i| &line[i..]).unwrap_or(line)
}

/// The byte pin: `std.tmh` is committed, derived output, and this is the
/// standing proof it is exactly `tmt interface`'s own printer output over
/// `std.tmc` (plus the generated notice) — never hand-edited. Mutation:
/// ANY change to the printer (RULING 25's `use`-line pass included, since
/// this pin was RED against the unpatched printer — see the task report)
/// that is not ALSO regenerated into the committed file.
#[test]
fn std_tmh_is_what_tmt_interface_prints() {
    assert_eq!(stdlib::HEADER_SOURCE, generate_std_tmh());
}

/// Regenerate `std.tmh` from `std.tmc`. Explicit and `#[ignore]`d, like the
/// program goldens: the file is derived output and is never edited by hand
/// (docs/tmt/stdlib.md (the shipped header)).
#[test]
#[ignore]
fn regen() {
    std::fs::write(std_tmh_path(), generate_std_tmh()).unwrap();
}

/// `stdlib::header()` (parsed from the committed `std.tmh`) must agree
/// with `stdlib::resolved()` (parsed from `std.tmc`, bodies and all) on
/// every exported routine's declared `writes` set — the one thing the
/// footprint inference reads off an external module (docs/tmt/language.md
/// (declarations)). Neither type is reachable from an integration test
/// (`Resolved` is crate-private), so this compares through the same
/// public surface both are built from: a FRESH `tmt interface std.tmc`
/// run (the source arm, independent of whatever is currently committed)
/// against the COMMITTED `std.tmh` text itself, both read by the
/// identical `qualified_routines`/`write_set_suffix` extraction
/// `header_roundtrip.rs`'s two-arm test uses. This also proves the F1
/// case specifically: `invertNumber`'s `preserves`-only shape must
/// compare EQUAL (both sides already publish the same reduced EFFECTIVE
/// set), not merely happen not to differ. Mutation: dropping the `writes`
/// clause from the printer entirely — VERIFIED by hand (see the task
/// report): with `tape_param_text` printing bare `tape NAME: ALPHABET`
/// (no `writes { … }` suffix at all), this test's `write_set_suffix`
/// comparison goes red on every routine (the byte pin above ALSO catches
/// that specific mutation, since std.tmh would go stale against the
/// broken printer's fresh output; this test is the one that would still
/// notice even if a regen had rewritten std.tmh to match the mutation,
/// since std.tmc's own resolved analysis — read here through the source
/// arm rather than the printer's parsed output — separately confirms the
/// SAME EFFECTIVE set was always what the contract meant).
#[test]
fn the_header_and_the_source_agree_on_every_declared_contract() {
    let source_text = {
        let dir = scratch("stdlib_header_contracts_source");
        let path = dir.join("std.tmc");
        std::fs::write(&path, stdlib::SOURCE).unwrap();
        let out = execute(&args(&["interface", path.to_str().unwrap()]))
            .unwrap_or_else(|e| panic!("interface std.tmc: {e}"));
        assert_eq!(out.code, 0, "{}", out.stderr);
        out.stdout
    };

    let source_routines = qualified_routines(&source_text);
    let header_routines = qualified_routines(stdlib::HEADER_SOURCE);

    assert!(
        !source_routines.is_empty(),
        "no routines parsed out of std.tmc's own freshly rendered header"
    );
    assert_eq!(
        source_routines.len(),
        header_routines.len(),
        "source: {:?}\nheader: {:?}",
        source_routines.keys().collect::<Vec<_>>(),
        header_routines.keys().collect::<Vec<_>>()
    );

    for (name, source_line) in &source_routines {
        let header_line = header_routines
            .get(name)
            .unwrap_or_else(|| panic!("`{name}` is missing from the committed std.tmh"));
        assert_eq!(
            write_set_suffix(source_line),
            write_set_suffix(header_line),
            "write sets disagree for `{name}`:\n source: {source_line}\n header: {header_line}"
        );
    }

    // Non-vacuity for the F1 case specifically: both `preserves`-only
    // routines must be present, on both sides, already collapsed to the
    // reduced effective set `{ '0', '1' }` (the alphabet `{ '_', '0', '1' }`
    // minus `'_'`) rather than a coincidental agreement over some other
    // shape.
    for name in [
        "std::binaryNumbersBare::invertNumber",
        "std::binaryNumbersBareVolatile::invertNumber",
    ] {
        let source_line = &source_routines[name];
        let header_line = &header_routines[name];
        assert!(
            write_set_suffix(source_line).contains("writes { '0', '1' }"),
            "{name}: source arm did not publish the reduced effective set: {source_line}"
        );
        assert!(
            write_set_suffix(header_line).contains("writes { '0', '1' }"),
            "{name}: committed std.tmh did not carry the reduced effective set: {header_line}"
        );
    }
}

/// Every exported stdlib graph is in the header, WITH its full body: a
/// count (12 — 8 in `binaryNumbers`, 4 in `binaryNumbersBare`, matching
/// `stdlib/mod.rs`'s own `the_volatile_twins_mirror_their_plain_
/// namespaces`'s `graft_sites == 12`) plus one body spot-check. Runs a
/// FRESH `tmt interface std.tmc`, not the committed `stdlib::
/// HEADER_SOURCE` constant: the committed file only ever changes via
/// `regen`, so checking it directly would pin static bytes rather than
/// exercise the printer, and could never independently catch a printer
/// regression (VERIFIED by hand: this exact mutation, applied against the
/// STATIC committed constant instead of a fresh run, left this test
/// green — see the task report). Mutation: a printer that renders a
/// graph's `state` blocks without their `rules` (an empty body, e.g.
/// `entry state walk { }`) — this still compiles (a state may legally
/// carry zero rules) and would silently make every library graft against
/// it produce a no-op instead of the real behavior, since nothing would
/// be left to splice. VERIFIED RED by hand (see the task report): with
/// `graph_lines`'s rule-printing loop deleted, the `['$'] -> goto done;`
/// spot-check below fails while the header still parses cleanly and the
/// routine count is unaffected.
#[test]
fn every_exported_stdlib_graph_is_in_the_header_with_its_body() {
    let dir = scratch("stdlib_header_graph_bodies");
    let path = dir.join("std.tmc");
    std::fs::write(&path, stdlib::SOURCE).unwrap();
    let out = execute(&args(&["interface", path.to_str().unwrap()]))
        .unwrap_or_else(|e| panic!("interface std.tmc: {e}"));
    assert_eq!(out.code, 0, "{}", out.stderr);
    let source_text = out.stdout;

    let count = source_text
        .lines()
        .filter(|l| l.trim_start().starts_with("export graph "))
        .count();
    assert_eq!(count, 12, "expected 12 exported stdlib graphs");

    assert!(
        source_text
            .contains("export graph goToNumberGraph(tape num: symbols writes {}, state done) {"),
        "goToNumberGraph's signature is missing or reformatted"
    );
    assert!(
        source_text.contains("entry state walk {"),
        "goToNumberGraph's body (its entry state) is missing"
    );
    assert!(
        source_text.contains("['$'] -> goto done;"),
        "goToNumberGraph's body (its rule) is missing"
    );
}
