//! Renders a bash completion script from the registry
//! (`completions::registry`). A pure text transform, like `zsh.rs`: it
//! knows nothing about PM-1 itself, so a new subcommand or flag reaches
//! the script by being registered, never by being special-cased here.
//! Mirrors the TM-1 `tmt` renderer
//! (`crates/turing-machine/src/completions/bash.rs`) line for line but
//! the command name.
//!
//! The script targets **bash 3.2** — macOS still ships it as `/bin/bash`,
//! and it is the oldest bash anyone plausibly completes in — so it uses
//! no associative arrays, no `mapfile`, and no `${var,,}`. It also runs
//! without the `bash-completion` package: every helper it needs is
//! defined in the script itself.
//!
//! # Shape
//!
//! One `_pmt` function, registered with `complete -o filenames -F _pmt
//! pmt`, plus a leaf function per registered (sub)command. `_pmt`
//! re-tokenizes `COMP_LINE` up to `COMP_POINT` itself rather than
//! reading `COMP_WORDS`: bash splits `COMP_WORDS` at every
//! `COMP_WORDBREAKS` character, and that set includes `=` and `:` by
//! default, so `--emit-ir=after:inline` would arrive as five words. Every
//! candidate is built as the FULL token the parser accepts, and one trim
//! step at the end strips the prefix up to the last word-break character
//! of the current word — which is exactly the part bash keeps. The
//! re-tokenizer splits on whitespace only: a path with a space or a quote
//! in it is not completed (bash quotes such a candidate on insert, but
//! a half-typed quoted word is cut at the wrong place first). A known
//! limit, not a bug to rediscover.
//!
//! What each registry shape becomes:
//!
//! * a `Value` flag completes its value when it is the previous word, and
//!   when the current word is `name=…` (both spellings the parser reads);
//! * an `OptionalEqualsValue` flag offers the bare flag plus one
//!   `name=choice` token per choice — never a space-separated value,
//!   which the parser would not read;
//! * a `SuffixFamily` offers one full flag per choice;
//! * an exclusive group withholds a flag once a group-mate is on the
//!   line, and any non-repeatable flag is withheld once it has been used
//!   — the two things zsh's `_arguments` does on its own;
//! * a file positional or value offers directories plus files matching
//!   the registered extensions (bash always traverses directories, so
//!   `FileHint::dirs` needs no separate rendering); `build`'s positional
//!   adds the manifest's target names by shelling out to `pmt build
//!   --list-targets` at completion time (docs/pmt/cli.md (pmt build)).
//!
//! `FlagSpec::requires` is not rendered, matching the zsh renderer.

use super::registry::{
    CommandSpec, FileHint, FlagKind, FlagSpec, Positional, PositionalHint, Registry, ValueHint,
    child_help, expand,
};

pub fn render(registry: &Registry) -> String {
    let root = registry
        .commands
        .iter()
        .find(|c| c.path.is_empty())
        .expect("registry always has a root entry");
    let leaves: Vec<&CommandSpec> = registry
        .commands
        .iter()
        .filter(|c| c.path.len() == 1)
        .collect();
    let mut groups: Vec<&str> = Vec::new();
    for command in registry.commands.iter().filter(|c| c.path.len() == 2) {
        let name = command.path[0].as_str();
        if !groups.contains(&name) {
            groups.push(name);
        }
    }

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(HELPERS);

    for leaf in &leaves {
        render_leaf(&mut out, leaf);
    }
    for group in &groups {
        for child in registry
            .commands
            .iter()
            .filter(|c| c.path.len() == 2 && c.path[0] == *group)
        {
            render_leaf(&mut out, child);
        }
    }

    render_main(&mut out, root, &leaves, &groups, registry);
    out.push_str("complete -o filenames -F _pmt pmt\n");
    out
}

const HEADER: &str = "\
# bash completion for pmt — generated by `pmt completions bash` from the CLI
# registry; do not hand-edit, regenerate with `pmt completions bash`.
# Runs on bash 3.2 and later, with or without the bash-completion package.

";

const HELPERS: &str = r#"# Add the words after the first argument that match it (the current word).
__pmt_words() {
  local cur=$1; shift
  COMPREPLY+=( $(compgen -W "$*" -- "$cur") )
}

# Add directories plus files carrying one of the given extensions; with no
# extension given, any file.
__pmt_files() {
  local cur=$1; shift
  if [ $# -eq 0 ]; then
    COMPREPLY+=( $(compgen -f -- "$cur") )
    return
  fi
  COMPREPLY+=( $(compgen -d -- "$cur") )
  local ext
  for ext in "$@"; do
    COMPREPLY+=( $(compgen -f -X "!*.$ext" -- "$cur") )
  done
}

__pmt_dirs() {
  COMPREPLY+=( $(compgen -d -- "$1") )
}

# The nearest manifest's target names, one per line from the binary itself
# (`NAME`, a tab, then `run` when the target carries a run block).
__pmt_targets() {
  local line targets=
  while IFS= read -r line; do
    targets="$targets ${line%%$'\t'*}"
  done < <(pmt build --list-targets 2>/dev/null)
  __pmt_words "$1" $targets
}

# Prepend $1 to every candidate (the `name=` head of a joined value).
__pmt_prefix() {
  local i
  for (( i=0; i<${#COMPREPLY[@]}; i++ )); do
    COMPREPLY[i]=$1${COMPREPLY[i]}
  done
}

# True when none of the given tokens is on the line before the cursor —
# as a whole word, or as the `token=` head of one.
__pmt_absent() {
  local tok w
  for tok in "$@"; do
    for w in "${__pmt_prior[@]}"; do
      case $w in "$tok"|"$tok="*) return 1 ;; esac
    done
  done
  return 0
}

# Withhold candidates already on the line, except the repeatable ones
# named in $1.
__pmt_unused() {
  local repeat=" $1 " c
  local -a kept
  for c in "${COMPREPLY[@]}"; do
    case $repeat in *" $c "*) kept+=("$c"); continue ;; esac
    __pmt_absent "$c" && kept+=("$c")
  done
  COMPREPLY=( "${kept[@]}" )
}

# bash replaces only the part of the current word after its last
# COMP_WORDBREAKS character (`=` and `:` are both in the default set), so
# strip that prefix from every candidate.
__pmt_trim() {
  local cur=$1 i c prefix=
  for (( i=${#cur}-1; i>=0; i-- )); do
    c=${cur:i:1}
    case $COMP_WORDBREAKS in *"$c"*) prefix=${cur:0:i+1}; break ;; esac
  done
  [ -n "$prefix" ] || return 0
  for (( i=0; i<${#COMPREPLY[@]}; i++ )); do
    COMPREPLY[i]=${COMPREPLY[i]#"$prefix"}
  done
}

"#;

/// Function name for a command path: `__pmt_leaf_compile`,
/// `__pmt_leaf_tape_block_new`.
fn leaf_name(path: &[String]) -> String {
    format!("__pmt_leaf_{}", path.join("_").replace('-', "_"))
}

fn render_leaf(out: &mut String, spec: &CommandSpec) {
    out.push_str(&format!("{}() {{\n", leaf_name(&spec.path)));

    // A value flag as the previous word: complete its value.
    let value_flags: Vec<&FlagSpec> = spec
        .flags
        .iter()
        .filter(|f| matches!(f.kind, FlagKind::Value(_)))
        .collect();
    if !value_flags.is_empty() {
        out.push_str("  case $prev in\n");
        for flag in &value_flags {
            let FlagKind::Value(hint) = &flag.kind else {
                unreachable!()
            };
            out.push_str(&format!(
                "    {}) {}; return ;;\n",
                flag.name,
                value_action(hint, "$cur", "")
            ));
        }
        out.push_str("  esac\n");
    }

    // The current word joined as `name=…`: the same value with the head
    // kept on every candidate (the trim step removes it again where bash
    // breaks the word at `=`).
    let joined: Vec<&FlagSpec> = spec
        .flags
        .iter()
        .filter(|f| {
            matches!(
                f.kind,
                FlagKind::Value(_) | FlagKind::OptionalEqualsValue(_)
            )
        })
        .collect();
    let mut arms: Vec<String> = Vec::new();
    for flag in &joined {
        let hint = match &flag.kind {
            FlagKind::Value(h) | FlagKind::OptionalEqualsValue(h) => h,
            _ => unreachable!(),
        };
        let action = match hint {
            ValueHint::Text => "return".to_string(),
            ValueHint::Choices(choices) => {
                let words: Vec<String> = choices
                    .iter()
                    .map(|c| format!("{}={c}", flag.name))
                    .collect();
                format!("__pmt_words \"$cur\" {}; return", words.join(" "))
            }
            ValueHint::File(_) | ValueHint::Directory => format!(
                "{}; __pmt_prefix \"{}=\"; return",
                value_action(hint, "${cur#*=}", ""),
                flag.name
            ),
        };
        arms.push(format!("    {}=*) {action} ;;\n", flag.name));
    }

    // Flags, once the current word starts with `-`.
    let mut plain: Vec<String> = Vec::new();
    let mut guarded: Vec<(String, Vec<String>)> = Vec::new();
    let mut repeatable: Vec<String> = Vec::new();
    for flag in &spec.flags {
        let mut tokens = expand(flag);
        if let FlagKind::OptionalEqualsValue(ValueHint::Choices(choices)) = &flag.kind {
            tokens.extend(choices.iter().map(|c| format!("{}={c}", flag.name)));
        }
        // A family is "repeatable" as a family — each member still
        // appears once — so only an ordinary repeatable flag is re-offered
        // after use (zsh's `*` prefix draws the same line).
        if flag.repeatable && !matches!(flag.kind, FlagKind::SuffixFamily(_)) {
            repeatable.extend(tokens.iter().cloned());
        }
        let mates: Vec<String> = match &flag.exclusive_group {
            Some(group) => spec
                .flags
                .iter()
                .filter(|f| f.name != flag.name && f.exclusive_group.as_deref() == Some(group))
                .map(|f| f.name.clone())
                .collect(),
            None => Vec::new(),
        };
        if mates.is_empty() {
            plain.extend(tokens);
        } else {
            for token in tokens {
                guarded.push((token, mates.clone()));
            }
        }
    }
    let mut flag_arm = String::new();
    flag_arm.push_str(&format!("      local flags=\"{}\"\n", plain.join(" ")));
    for (token, mates) in &guarded {
        flag_arm.push_str(&format!(
            "      __pmt_absent {} && flags=\"$flags {token}\"\n",
            mates.join(" ")
        ));
    }
    flag_arm.push_str("      __pmt_words \"$cur\" $flags\n");
    flag_arm.push_str(&format!(
        "      __pmt_unused \"{}\"\n      return ;;\n",
        repeatable.join(" ")
    ));
    arms.push(format!("    -*)\n{flag_arm}"));

    out.push_str("  case $cur in\n");
    for arm in &arms {
        out.push_str(arm);
    }
    out.push_str("  esac\n");

    // The positional.
    if let Some(action) = positional_action(&spec.positional) {
        out.push_str(&format!("  {action}\n"));
    }
    out.push_str("}\n\n");
}

/// The helper call completing one value hint for `cur` (a shell
/// expression), with an optional `; …` suffix.
fn value_action(hint: &ValueHint, cur: &str, suffix: &str) -> String {
    let body = match hint {
        ValueHint::Text => "return".to_string(),
        ValueHint::Choices(choices) => format!("__pmt_words \"{cur}\" {}", choices.join(" ")),
        ValueHint::File(file) => files_call(file, cur),
        ValueHint::Directory => format!("__pmt_dirs \"{cur}\""),
    };
    format!("{body}{suffix}")
}

fn files_call(hint: &FileHint, cur: &str) -> String {
    if hint.extensions.is_empty() {
        format!("__pmt_files \"{cur}\"")
    } else {
        format!("__pmt_files \"{cur}\" {}", hint.extensions.join(" "))
    }
}

fn positional_action(positional: &Positional) -> Option<String> {
    let hint = match positional {
        Positional::None => return None,
        Positional::One(hint) | Positional::OneOrMore(hint) => hint,
    };
    match hint {
        PositionalHint::File(file) => Some(files_call(file, "$cur")),
        PositionalHint::FilesOrTargets(file) => Some(format!(
            "{}; __pmt_targets \"$cur\"",
            files_call(file, "$cur")
        )),
        PositionalHint::Choices(choices) => {
            let words: Vec<&str> = choices.iter().map(|c| c.value.as_str()).collect();
            Some(format!("__pmt_words \"$cur\" {}", words.join(" ")))
        }
        PositionalHint::Text => None,
    }
}

fn render_main(
    out: &mut String,
    root: &CommandSpec,
    leaves: &[&CommandSpec],
    groups: &[&str],
    registry: &Registry,
) {
    let Positional::One(PositionalHint::Choices(choices)) = &root.positional else {
        panic!("root positional must be a subcommand-name choice list");
    };
    let subs: Vec<&str> = choices.iter().map(|c| c.value.as_str()).collect();
    let root_flags: Vec<String> = root.flags.iter().flat_map(expand).collect();

    out.push_str(
        "_pmt() {\n\
         \x20 # Re-tokenize the line up to the cursor on whitespace, so a word is\n\
         \x20 # whole regardless of COMP_WORDBREAKS.\n\
         \x20 local line=${COMP_LINE:0:$COMP_POINT}\n\
         \x20 local -a words __pmt_prior\n\
         \x20 read -r -a words <<< \"$line\"\n\
         \x20 local cur= n=${#words[@]}\n\
         \x20 case $line in\n\
         \x20   *[[:space:]]) ;;\n\
         \x20   *) cur=${words[n-1]}; n=$((n-1)) ;;\n\
         \x20 esac\n\
         \x20 __pmt_prior=( \"${words[@]:0:n}\" )\n\
         \x20 local prev=\n\
         \x20 [ $n -ge 1 ] && prev=${__pmt_prior[n-1]}\n\
         \x20 COMPREPLY=()\n\
         \n\
         \x20 # The subcommand is the first bare word after the command name.\n\
         \x20 local sub= action= i\n\
         \x20 for (( i=1; i<n; i++ )); do\n\
         \x20   case ${__pmt_prior[i]} in -*) ;; *) sub=${__pmt_prior[i]}; break ;; esac\n\
         \x20 done\n\
         \n\
         \x20 case $sub in\n",
    );
    out.push_str(&format!(
        "    \"\")\n      local subs=\"{}\"\n      case $cur in\n        -*) __pmt_words \"$cur\" {} ;;\n        *) __pmt_words \"$cur\" $subs ;;\n      esac\n      ;;\n",
        subs.join(" "),
        root_flags.join(" ")
    ));
    for leaf in leaves {
        out.push_str(&format!(
            "    {}) {} ;;\n",
            leaf.path[0],
            leaf_name(&leaf.path)
        ));
    }
    for group in groups {
        let children: Vec<&CommandSpec> = registry
            .commands
            .iter()
            .filter(|c| c.path.len() == 2 && c.path[0] == *group)
            .collect();
        let names: Vec<&str> = children.iter().map(|c| c.path[1].as_str()).collect();
        out.push_str(&format!(
            "    {group})\n      # The action is the next bare word after the group name.\n      for (( i=i+1; i<n; i++ )); do\n        case ${{__pmt_prior[i]}} in -*) ;; *) action=${{__pmt_prior[i]}}; break ;; esac\n      done\n      case $action in\n        \"\") __pmt_words \"$cur\" {} ;;\n",
            names.join(" ")
        ));
        for child in &children {
            // The gloss is not shown by bash; it documents the arm.
            out.push_str(&format!(
                "        {}) {} ;; # {}\n",
                child.path[1],
                leaf_name(&child.path),
                child_help(child)
            ));
        }
        out.push_str("      esac\n      ;;\n");
    }
    out.push_str("  esac\n  __pmt_trim \"$cur\"\n}\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::completions::registry::registry;

    fn script() -> String {
        render(&registry())
    }

    #[test]
    fn registers_the_function_with_filename_handling() {
        let s = script();
        assert!(s.starts_with("# bash completion for pmt"), "{s}");
        assert!(
            s.trim_end().ends_with("complete -o filenames -F _pmt pmt"),
            "{s}"
        );
    }

    #[test]
    fn lists_every_top_level_subcommand_as_a_root_candidate() {
        let reg = registry();
        let root = reg.commands.iter().find(|c| c.path.is_empty()).unwrap();
        let Positional::One(PositionalHint::Choices(choices)) = &root.positional else {
            panic!("root positional is the subcommand list");
        };
        let names: Vec<&str> = choices.iter().map(|c| c.value.as_str()).collect();
        assert!(names.contains(&"tape-block") && names.contains(&"completions"));
        let s = render(&reg);
        assert!(
            s.contains(&format!("local subs=\"{}\"", names.join(" "))),
            "the root word list is the registry's subcommand list:\n{s}"
        );
    }

    #[test]
    fn fno_expands_to_one_flag_per_pass() {
        let s = script();
        for pass in crate::optimizer::pass_names() {
            assert!(s.contains(&format!("--fno-{pass}")), "--fno-{pass}:\n{s}");
        }
        assert!(
            !s.contains("--fno- "),
            "the bare prefix is not a candidate:\n{s}"
        );
    }

    #[test]
    fn emit_ir_offers_the_bare_flag_and_equals_joined_stages() {
        let s = script();
        assert!(s.contains(" --emit-ir "), "bare --emit-ir:\n{s}");
        assert!(s.contains("--emit-ir=lowered"), "{s}");
        assert!(s.contains("--emit-ir=after:inline"), "{s}");
    }

    #[test]
    fn exclusive_flags_are_guarded_by_their_group_mates() {
        let s = script();
        assert!(
            s.contains("__pmt_absent -O1 && flags=\"$flags -O0\""),
            "{s}"
        );
        assert!(
            s.contains("__pmt_absent -O0 && flags=\"$flags -O1\""),
            "{s}"
        );
        // `build`'s profile pair too.
        assert!(
            s.contains("__pmt_absent --release && flags=\"$flags --debug\""),
            "{s}"
        );
    }

    #[test]
    fn positionals_are_extension_filtered() {
        let s = script();
        assert!(
            s.contains("__pmt_files \"$cur\" pmc\n"),
            "compile takes .pmc:\n{s}"
        );
        assert!(
            s.contains("__pmt_files \"$cur\" pmo pmx\n"),
            "dis takes .pmo/.pmx:\n{s}"
        );
        assert!(
            s.contains("__pmt_files \"$cur\" pmc pma\n"),
            "lint/fmt take sources:\n{s}"
        );
    }

    #[test]
    fn build_positional_adds_manifest_targets() {
        let s = script();
        assert!(
            s.contains("__pmt_files \"$cur\" pmc pma pmo; __pmt_targets \"$cur\""),
            "{s}"
        );
        assert!(s.contains("pmt build --list-targets 2>/dev/null"), "{s}");
    }

    #[test]
    fn value_flags_complete_their_values_after_the_flag() {
        let s = script();
        assert!(s.contains("--lang) __pmt_words \"$cur\" pmc pma"), "{s}");
        assert!(s.contains("-L) __pmt_dirs \"$cur\""), "{s}");
        assert!(s.contains("--map) __pmt_files \"$cur\" pmx.map"), "{s}");
        // Free text completes nothing, and says so by returning early.
        assert!(s.contains("-l) return"), "{s}");
    }
}
