//! Renders a fish completion script from the registry
//! (`completions::registry`). A pure text transform, like `zsh.rs` and
//! `bash.rs`: it knows nothing about PM-1 itself, so a new subcommand or
//! flag reaches the script by being registered, never by being
//! special-cased here. Mirrors the TM-1 `tmt` renderer
//! (`crates/turing-machine/src/completions/fish.rs`) line for line but
//! the command name.
//!
//! fish completions are declarative — one `complete -c pmt …` statement
//! per candidate, each guarded by a `-n` condition that says when it
//! applies — so unlike the bash script there is no function to run:
//! fish evaluates the conditions itself. What each registry shape
//! becomes:
//!
//! * the root's subcommand names are offered under `__fish_use_subcommand`,
//!   each with its gloss; a group's actions under "the group is on the
//!   line and none of its actions is yet"; a leaf's flags under "the
//!   subcommand (and, for a group's action, the action) is on the line";
//! * a flag's spelling decides its option kind: `--name` is `-l name`, a
//!   one-letter `-x` is `-s x`, and a longer single-dash flag such as
//!   `-O0` or `-Werror` is an old-style `-o O0` option;
//! * a `Value` flag carries its value shape — `-x -a 'choices'` for a
//!   closed set, `-r -F` for any file, `-r -f -a '(__fish_complete_suffix
//!   .ext)'` per registered extension, `-x -a '(__fish_complete_directories)'`
//!   for a directory, bare `-x` for free text;
//! * an `OptionalEqualsValue` flag is the bare option plus the
//!   `name=choice` tokens, the latter offered only once the current
//!   token already starts with `name=` — never a space-separated value,
//!   which the parser would not read;
//! * a `SuffixFamily` is one long option per choice;
//! * an exclusive group adds `and not __fish_seen_argument <mate>` for
//!   each group-mate, so a flag disappears once a mate is on the line;
//!   fish itself withholds an option already used, which is what
//!   `repeatable` would otherwise have to express;
//! * a file positional offers `__fish_complete_suffix` per extension
//!   (that helper includes directories, so `FileHint::dirs` needs no
//!   separate rendering); `build`'s positional adds the manifest's
//!   target names by shelling out to `pmt build --list-targets` at
//!   completion time (docs/pmt/cli.md (pmt build)).
//!
//! `FlagSpec::requires` is not rendered, matching the zsh renderer.

use super::registry::{
    CommandSpec, FileHint, FlagKind, Positional, PositionalHint, Registry, ValueHint, child_help,
    expand,
};

pub fn render(registry: &Registry) -> String {
    let root = registry
        .commands
        .iter()
        .find(|c| c.path.is_empty())
        .expect("registry always has a root entry");
    let mut groups: Vec<&str> = Vec::new();
    for command in registry.commands.iter().filter(|c| c.path.len() == 2) {
        let name = command.path[0].as_str();
        if !groups.contains(&name) {
            groups.push(name);
        }
    }

    let mut out = String::new();
    out.push_str(
        "# fish completion for pmt — generated by `pmt completions fish` from the CLI\n\
         # registry; do not hand-edit, regenerate with `pmt completions fish`.\n\n\
         # Positional arguments never default to file names; each subcommand below\n\
         # declares what its own positional accepts.\n\
         complete -c pmt -f\n\n",
    );

    // Root: global flags and the subcommand names.
    out.push_str("# pmt\n");
    for flag in &root.flags {
        for token in expand(flag) {
            out.push_str(&format!(
                "complete -c pmt -n '__fish_use_subcommand' {} -d '{}'\n",
                option(&token),
                esc(&flag.help)
            ));
        }
    }
    let Positional::One(PositionalHint::Choices(choices)) = &root.positional else {
        panic!("root positional must be a subcommand-name choice list");
    };
    for choice in choices {
        out.push_str(&format!(
            "complete -c pmt -n '__fish_use_subcommand' -a {} -d '{}'\n",
            choice.value,
            esc(&choice.help)
        ));
    }
    out.push('\n');

    for leaf in registry.commands.iter().filter(|c| c.path.len() == 1) {
        let seen = format!("__fish_seen_subcommand_from {}", leaf.path[0]);
        render_leaf(&mut out, leaf, &seen);
    }

    for group in &groups {
        let children: Vec<&CommandSpec> = registry
            .commands
            .iter()
            .filter(|c| c.path.len() == 2 && c.path[0] == *group)
            .collect();
        let names: Vec<&str> = children.iter().map(|c| c.path[1].as_str()).collect();
        out.push_str(&format!("# pmt {group}\n"));
        for child in &children {
            out.push_str(&format!(
                "complete -c pmt -n '__fish_seen_subcommand_from {group}; and not __fish_seen_subcommand_from {}' -f -a {} -d '{}'\n",
                names.join(" "),
                child.path[1],
                esc(child_help(child))
            ));
        }
        out.push('\n');
        for child in &children {
            let seen = format!(
                "__fish_seen_subcommand_from {group}; and __fish_seen_subcommand_from {}",
                child.path[1]
            );
            render_leaf(&mut out, child, &seen);
        }
    }
    out
}

fn render_leaf(out: &mut String, spec: &CommandSpec, seen: &str) {
    out.push_str(&format!("# pmt {}\n", spec.path.join(" ")));
    for flag in &spec.flags {
        let mut condition = seen.to_string();
        if let Some(group) = &flag.exclusive_group {
            for mate in spec
                .flags
                .iter()
                .filter(|f| f.name != flag.name && f.exclusive_group.as_deref() == Some(group))
            {
                condition.push_str(&format!(
                    "; and not __fish_seen_argument {}",
                    option(&mate.name)
                ));
            }
        }
        let desc = esc(&flag.help);
        match &flag.kind {
            FlagKind::Boolean => out.push_str(&format!(
                "complete -c pmt -n '{condition}' {} -d '{desc}'\n",
                option(&flag.name)
            )),
            FlagKind::Value(hint) => out.push_str(&format!(
                "complete -c pmt -n '{condition}' {} {} -d '{desc}'\n",
                option(&flag.name),
                value_shape(hint)
            )),
            FlagKind::OptionalEqualsValue(hint) => {
                out.push_str(&format!(
                    "complete -c pmt -n '{condition}' {} -d '{desc}'\n",
                    option(&flag.name)
                ));
                if let ValueHint::Choices(choices) = hint {
                    let tokens: Vec<String> = choices
                        .iter()
                        .map(|c| format!("{}={c}", flag.name))
                        .collect();
                    out.push_str(&format!(
                        "complete -c pmt -n '{condition}; and string match -q -- \\'{}=*\\' (commandline -ct)' -f -a '{}' -d '{desc}'\n",
                        flag.name,
                        tokens.join(" ")
                    ));
                }
            }
            FlagKind::SuffixFamily(_) => {
                for token in expand(flag) {
                    out.push_str(&format!(
                        "complete -c pmt -n '{condition}' {} -d '{desc}'\n",
                        option(&token)
                    ));
                }
            }
        }
    }
    match &spec.positional {
        Positional::None => {}
        Positional::One(hint) | Positional::OneOrMore(hint) => match hint {
            PositionalHint::File(file) => {
                for entry in suffix_completions(file) {
                    out.push_str(&format!("complete -c pmt -n '{seen}' -f -a '{entry}'\n"));
                }
            }
            PositionalHint::FilesOrTargets(file) => {
                for entry in suffix_completions(file) {
                    out.push_str(&format!("complete -c pmt -n '{seen}' -f -a '{entry}'\n"));
                }
                out.push_str(&format!(
                    "complete -c pmt -n '{seen}' -f -a '(pmt build --list-targets 2>/dev/null | string replace -r \\'\\\\t.*\\' \\'\\')'\n"
                ));
            }
            PositionalHint::Choices(choices) => {
                for choice in choices {
                    out.push_str(&format!(
                        "complete -c pmt -n '{seen}' -f -a {} -d '{}'\n",
                        choice.value,
                        esc(&choice.help)
                    ));
                }
            }
            PositionalHint::Text => {}
        },
    }
    out.push('\n');
}

/// The `complete` option switch for a flag token: `--name` → `-l name`,
/// a one-letter `-x` → `-s x`, anything longer with one dash → `-o name`
/// (fish's "old-style" single-dash long option).
fn option(token: &str) -> String {
    if let Some(long) = token.strip_prefix("--") {
        format!("-l {long}")
    } else {
        let short = token.strip_prefix('-').unwrap_or(token);
        if short.len() == 1 {
            format!("-s {short}")
        } else {
            format!("-o {short}")
        }
    }
}

/// The argument shape switches for a `Value` flag.
fn value_shape(hint: &ValueHint) -> String {
    match hint {
        ValueHint::Text => "-x".to_string(),
        ValueHint::Choices(choices) => format!("-x -a '{}'", choices.join(" ")),
        ValueHint::File(file) => {
            if file.extensions.is_empty() {
                "-r -F".to_string()
            } else {
                // One `-a` per extension would need one `complete` line
                // each; a single line takes them as one argument list of
                // command substitutions instead (fish expands `-a`'s
                // string like a command line, so each substitution
                // contributes its lines to one candidate list).
                let calls: Vec<String> = suffix_completions(file);
                format!("-r -f -a '{}'", calls.join(" "))
            }
        }
        ValueHint::Directory => "-x -a '(__fish_complete_directories)'".to_string(),
    }
}

/// One `(__fish_complete_suffix .ext)` substitution per registered
/// extension (the helper offers directories alongside, so a `dirs` hint
/// needs nothing extra).
fn suffix_completions(hint: &FileHint) -> Vec<String> {
    hint.extensions
        .iter()
        .map(|ext| format!("(__fish_complete_suffix .{ext})"))
        .collect()
}

/// Escape for the inside of a fish single-quoted string: only `\` and
/// `'` are special there.
fn esc(text: &str) -> String {
    text.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::completions::registry::registry;

    fn script() -> String {
        render(&registry())
    }

    fn line_with(s: &str, needle: &str) -> String {
        s.lines()
            .find(|l| l.contains(needle))
            .unwrap_or_else(|| panic!("no line contains {needle:?}:\n{s}"))
            .to_string()
    }

    #[test]
    fn disables_file_completion_globally_then_declares_subcommands() {
        let s = script();
        assert!(s.starts_with("# fish completion for pmt"), "{s}");
        assert!(s.contains("\ncomplete -c pmt -f\n"), "{s}");
        assert_eq!(
            line_with(&s, "-a compile "),
            "complete -c pmt -n '__fish_use_subcommand' -a compile -d '.pmc source -> .pmo object (-S for .pma, --emit-ir for CFG JSON)'"
        );
        assert!(
            s.contains("-n '__fish_use_subcommand' -l version -d"),
            "{s}"
        );
    }

    #[test]
    fn flags_are_classified_as_long_short_or_old_style() {
        let s = script();
        assert_eq!(
            line_with(&s, "-l strip-debugger"),
            "complete -c pmt -n '__fish_seen_subcommand_from compile' -l strip-debugger -d 'drop `brk` at codegen'"
        );
        assert!(
            s.contains("-n '__fish_seen_subcommand_from compile' -s g -d"),
            "{s}"
        );
        assert!(
            s.contains("-n '__fish_seen_subcommand_from compile' -o Werror -d"),
            "{s}"
        );
    }

    #[test]
    fn exclusive_flags_are_withheld_once_a_group_mate_is_present() {
        let s = script();
        assert_eq!(
            line_with(&s, "-o O0 -d 'optimization level O0 (default)'"),
            "complete -c pmt -n '__fish_seen_subcommand_from compile; and not __fish_seen_argument -o O1' -o O0 -d 'optimization level O0 (default)'"
        );
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from build; and not __fish_seen_argument -l release' -l debug"
            ),
            "{s}"
        );
    }

    #[test]
    fn fno_expands_to_one_long_option_per_pass() {
        let s = script();
        for pass in crate::optimizer::pass_names() {
            assert!(
                s.contains(&format!(" -l fno-{pass} -d")),
                "--fno-{pass}:\n{s}"
            );
        }
    }

    #[test]
    fn emit_ir_is_bare_or_equals_joined_only() {
        let s = script();
        assert!(
            s.contains("-n '__fish_seen_subcommand_from compile' -l emit-ir -d"),
            "{s}"
        );
        let joined = line_with(&s, "-a '--emit-ir=lowered --emit-ir=final");
        assert!(
            joined.contains("string match -q -- \\'--emit-ir=*\\' (commandline -ct)"),
            "joined tokens are offered only once the head is typed:\n{joined}"
        );
        assert!(joined.contains("--emit-ir=after:inline"), "{joined}");
        assert!(
            !s.contains("-l emit-ir -r"),
            "never a space-separated stage:\n{s}"
        );
    }

    #[test]
    fn value_flags_carry_their_value_shapes() {
        let s = script();
        assert!(s.contains(" -l lang -x -a 'pmc pma' -d"), "{s}");
        assert!(
            s.contains(" -s L -x -a '(__fish_complete_directories)' -d"),
            "{s}"
        );
        assert!(
            s.contains("-n '__fish_seen_subcommand_from compile' -s o -r -F -d"),
            "{s}"
        );
        assert!(
            s.contains(" -l map -r -f -a '(__fish_complete_suffix .pmx.map)' -d"),
            "{s}"
        );
        assert!(s.contains(" -s l -x -d"), "{s}");
    }

    #[test]
    fn positionals_are_extension_filtered_and_build_adds_targets() {
        let s = script();
        assert!(
            s.contains(
                "complete -c pmt -n '__fish_seen_subcommand_from compile' -f -a '(__fish_complete_suffix .pmc)'\n"
            ),
            "{s}"
        );
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from lint' -f -a '(__fish_complete_suffix .pma)'"
            ),
            "{s}"
        );
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from build' -f -a '(pmt build --list-targets 2>/dev/null | string replace -r \\'\\\\t.*\\' \\'\\')'"
            ),
            "{s}"
        );
        // A choice positional lists each word with its gloss.
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from completions' -f -a zsh -d 'Z shell completion script'"
            ),
            "{s}"
        );
    }

    #[test]
    fn groups_offer_actions_then_the_action_flags() {
        let s = script();
        assert_eq!(
            line_with(&s, "-a new -d"),
            "complete -c pmt -n '__fish_seen_subcommand_from tape-block; and not __fish_seen_subcommand_from build new set show' -f -a new -d 'write a blank .pmt template sized to an executable'"
        );
        // The action's flags are guarded by the action, and `--in-place`
        // additionally by its `-o` group-mate.
        assert!(
            s.contains(
                "-n '__fish_seen_subcommand_from tape-block; and __fish_seen_subcommand_from set; and not __fish_seen_argument -s o' -l in-place"
            ),
            "{s}"
        );
    }

    #[test]
    fn an_apostrophe_in_a_description_is_escaped() {
        let s = script();
        assert!(
            s.contains("-d 'repin a tape\\'s glyphs (KEY=GLYPHS)'"),
            "{s}"
        );
    }
}
