//! Shell completion for `pmt` (docs/pmt/cli.md (pmt completions)). `pmt` is
//! hand-rolled (no clap — deliberately, per the workspace's minimal-
//! dependency policy), so a completion script can't be generated by a
//! framework the way a clap-based CLI gets `clap_complete` for free.
//! Instead, [`registry::registry`] is the single in-crate description of
//! the CLI surface (subcommands, flags, positional file-extension
//! filters), and each shell renderer (currently [`zsh`]) is a pure text
//! transform over it. Library code here never prints — `cli::completions`
//! calls [`render`] and hands the string back for `bin/pmt.rs` to print,
//! per the thin-renderer rule (`docs/pmt/cli.md`).
//!
//! The registry can drift from the real parser if a flag is added to
//! `cli/build.rs` / `cli/inspect.rs` / `cli/run.rs` without a matching
//! registry update — nothing in the type system prevents that for a
//! hand-rolled parser. `crates/post-machine/tests/completions_registry.rs`
//! is the drift guard: it probes the actual parser with every registry
//! entry, and cross-checks the `--fno-<pass>` / `--emit-ir=after:<pass>`
//! choices against the optimizer's own pass-name list rather than a
//! retyped copy.

pub mod registry;
mod zsh;

/// A shell `pmt completions` can target. All three are *recognized* (so
/// `pmt completions <TAB>` lists them and an unknown name is a clear
/// error rather than "unknown shell"), but only zsh renders today; bash
/// and fish are a documented follow-on once zsh has proven the registry
/// (docs/pmt/cli.md (pmt completions)).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shell {
    Zsh,
    Bash,
    Fish,
}

pub fn parse_shell(name: &str) -> Result<Shell, String> {
    match name {
        "zsh" => Ok(Shell::Zsh),
        "bash" => Ok(Shell::Bash),
        "fish" => Ok(Shell::Fish),
        other => Err(format!(
            "unknown shell `{other}` (want one of: zsh, bash, fish)"
        )),
    }
}

/// Render the completion script for `shell`, or an error naming it as a
/// recognized-but-not-yet-implemented follow-on.
pub fn render(shell: Shell) -> Result<String, String> {
    match shell {
        Shell::Zsh => Ok(zsh::render(&registry::registry())),
        Shell::Bash => Err(
            "bash completion is not implemented yet (zsh shipped first; \
             bash and fish are tracked as follow-ons)"
                .to_string(),
        ),
        Shell::Fish => Err(
            "fish completion is not implemented yet (zsh shipped first; \
             bash and fish are tracked as follow-ons)"
                .to_string(),
        ),
    }
}
