//! Renders a zsh `#compdef` completion function from the registry
//! (`completions::registry`). Follows the standard "git-style" nested
//! `_arguments -C` + `->state` idiom (`man zshcompsys`): the root
//! dispatcher consumes the subcommand name via `'1: :->cmds'` and
//! `'*::arg:->args'`, then a per-subcommand function (nested one level
//! deeper for `tape`/`ir`) completes that subcommand's own flags and
//! positional. Because the outer call used `-C`, a nested `_arguments`
//! call automatically re-bases its own positional numbering to start
//! after the words already consumed — this is what lets every leaf
//! function treat its OWN positional as `1`/`*` without knowing how deep
//! it sits in the tree.

use super::registry::{
    CommandSpec, FileHint, FlagKind, FlagSpec, Positional, PositionalHint, Registry, ValueHint,
};

pub fn render(registry: &Registry) -> String {
    let root = registry
        .commands
        .iter()
        .find(|c| c.path.is_empty())
        .expect("registry always has a root entry");
    let leaves: Vec<&CommandSpec> = registry
        .commands
        .iter()
        .filter(|c| c.path.len() == 1)
        .collect();

    let mut group_names: Vec<&str> = Vec::new();
    for command in registry.commands.iter().filter(|c| c.path.len() == 2) {
        let name = command.path[0].as_str();
        if !group_names.contains(&name) {
            group_names.push(name);
        }
    }

    let mut out = String::new();
    out.push_str("#compdef pmt\n");
    out.push_str(
        "# Generated by `pmt completions zsh` from the CLI registry — do not hand-edit;\n",
    );
    out.push_str("# regenerate with `pmt completions zsh` (docs/cli.md (pmt completions)).\n\n");

    render_root(&mut out, root, &leaves, &group_names);
    out.push('\n');

    for leaf in &leaves {
        render_leaf(&mut out, &function_name(&leaf.path), leaf);
        out.push('\n');
    }

    for group in &group_names {
        let children: Vec<&CommandSpec> = registry
            .commands
            .iter()
            .filter(|c| c.path.len() == 2 && c.path[0] == *group)
            .collect();
        render_group(&mut out, group, &children);
        out.push('\n');
        for child in &children {
            render_leaf(&mut out, &function_name(&child.path), child);
            out.push('\n');
        }
    }

    out.push_str("_pmt \"$@\"\n");
    out
}

fn function_name(path: &[String]) -> String {
    format!("_pmt_{}", path.join("_"))
}

fn render_root(out: &mut String, root: &CommandSpec, leaves: &[&CommandSpec], groups: &[&str]) {
    let Positional::One(PositionalHint::Choices(choices)) = &root.positional else {
        panic!("root positional must be a subcommand-name choice list");
    };

    out.push_str("_pmt() {\n");
    out.push_str("  local -a subcommands\n");
    out.push_str("  subcommands=(\n");
    for choice in choices {
        out.push_str(&format!(
            "    '{}:{}'\n",
            zsh_escape_word(&choice.value),
            zsh_escape_desc(&choice.help)
        ));
    }
    out.push_str("  )\n");
    out.push_str("  _arguments -C \\\n");
    // --help/-h/--version are terminal: `(- *)` means "once this is
    // matched, no other argument on the line is required or offered".
    let help = root.flags.iter().find(|f| f.name == "--help");
    let version = root.flags.iter().find(|f| f.name == "--version");
    if let Some(help) = help {
        out.push_str(&format!(
            "    '(- *)'{{-h,--help}}'[{}]' \\\n",
            zsh_escape_desc(&help.help)
        ));
    }
    if let Some(version) = version {
        out.push_str(&format!(
            "    '(- *)'--version'[{}]' \\\n",
            zsh_escape_desc(&version.help)
        ));
    }
    out.push_str("    '1: :->cmds' \\\n");
    out.push_str("    '*::arg:->args'\n\n");
    out.push_str("  case $state in\n");
    out.push_str("    cmds)\n");
    out.push_str("      _describe -t commands 'pmt subcommand' subcommands\n");
    out.push_str("      ;;\n");
    out.push_str("    args)\n");
    out.push_str("      case $words[1] in\n");
    for leaf in leaves {
        out.push_str(&format!(
            "        {}) {} ;;\n",
            leaf.path[0],
            function_name(&leaf.path)
        ));
    }
    for group in groups {
        out.push_str(&format!("        {group}) _pmt_{group} ;;\n"));
    }
    out.push_str("      esac\n");
    out.push_str("      ;;\n");
    out.push_str("  esac\n");
    out.push_str("}\n");
}

fn render_group(out: &mut String, group: &str, children: &[&CommandSpec]) {
    out.push_str(&format!("_pmt_{group}() {{\n"));
    out.push_str("  local -a subcommands\n");
    out.push_str("  subcommands=(\n");
    for child in children {
        let name = &child.path[1];
        let help = super::registry::child_help(child);
        out.push_str(&format!(
            "    '{}:{}'\n",
            zsh_escape_word(name),
            zsh_escape_desc(help)
        ));
    }
    out.push_str("  )\n");
    // `-C` here (matching the root's) is what lets each child's OWN
    // nested `_arguments` call re-base its positional numbering to start
    // after "tape build"/"ir graph" rather than after just "tape"/"ir".
    out.push_str("  _arguments -C \\\n");
    out.push_str("    '1: :->subs' \\\n");
    out.push_str("    '*::arg:->args'\n\n");
    out.push_str("  case $state in\n");
    out.push_str("    subs)\n");
    out.push_str(&format!(
        "      _describe -t commands 'pmt {group} subcommand' subcommands\n"
    ));
    out.push_str("      ;;\n");
    out.push_str("    args)\n");
    out.push_str("      case $words[1] in\n");
    for child in children {
        out.push_str(&format!(
            "        {}) {} ;;\n",
            child.path[1],
            function_name(&child.path)
        ));
    }
    out.push_str("      esac\n");
    out.push_str("      ;;\n");
    out.push_str("  esac\n");
    out.push_str("}\n");
}

fn render_leaf(out: &mut String, fn_name: &str, spec: &CommandSpec) {
    let mut lines: Vec<String> = Vec::new();
    for flag in &spec.flags {
        lines.extend(flag_lines(flag, &spec.flags));
    }
    lines.extend(positional_lines(&spec.positional));

    out.push_str(&format!("{fn_name}() {{\n"));
    if lines.is_empty() {
        out.push_str("  _arguments\n");
    } else {
        out.push_str("  _arguments \\\n");
        for (i, line) in lines.iter().enumerate() {
            let continuation = if i + 1 < lines.len() { " \\" } else { "" };
            out.push_str(&format!("    {line}{continuation}\n"));
        }
    }
    out.push_str("}\n");
}

/// The `(other1 other2)` exclusion prefix for a flag's group-mates, or
/// empty if it has none.
fn exclusive_prefix(flag: &FlagSpec, all: &[FlagSpec]) -> String {
    let Some(group) = &flag.exclusive_group else {
        return String::new();
    };
    let others: Vec<&str> = all
        .iter()
        .filter(|f| f.name != flag.name && f.exclusive_group.as_deref() == Some(group.as_str()))
        .map(|f| f.name.as_str())
        .collect();
    if others.is_empty() {
        String::new()
    } else {
        format!("({})", others.join(" "))
    }
}

fn flag_lines(flag: &FlagSpec, all: &[FlagSpec]) -> Vec<String> {
    let excl = exclusive_prefix(flag, all);
    let repeat = if flag.repeatable { "*" } else { "" };
    let desc = zsh_escape_desc(&flag.help);

    match &flag.kind {
        FlagKind::Boolean => {
            vec![format!("'{repeat}{excl}{}[{desc}]'", flag.name)]
        }
        FlagKind::Value(hint) => {
            vec![format!(
                "'{repeat}{excl}{}[{desc}]:{}:{}'",
                flag.name,
                value_message(hint),
                value_action(hint)
            )]
        }
        FlagKind::OptionalEqualsValue(hint) => {
            // `name=-` (not `name`): the value, if given, is only ever
            // accepted joined with `=` — never as a following bare word
            // (docs/cli.md `--emit-ir[=STAGE]`; `take_emit_ir` bypasses
            // `Args::value`, so a space-separated stage is never read).
            // The DOUBLE colon before the message (`man zshcompsys`
            // "Specifying Options": "in the second form [`::`] it is
            // optional") is load-bearing, not decorative — a single
            // colon would tell `_arguments` this option always needs a
            // value, rejecting the bare `--emit-ir` the real parser
            // accepts (defaults to `final`).
            vec![format!(
                "'{excl}{}=-[{desc}]::{}:{}'",
                flag.name,
                value_message(hint),
                value_action(hint)
            )]
        }
        FlagKind::SuffixFamily(choices) => choices
            .iter()
            .map(|choice| format!("'{excl}{}{choice}[{desc}]'", flag.name))
            .collect(),
    }
}

fn value_message(hint: &ValueHint) -> &'static str {
    match hint {
        ValueHint::Text | ValueHint::Choices(_) => "value",
        ValueHint::File(_) => "file",
        ValueHint::Directory => "dir",
    }
}

fn value_action(hint: &ValueHint) -> String {
    match hint {
        ValueHint::Text => String::new(),
        ValueHint::Choices(choices) => {
            let words: Vec<String> = choices.iter().map(|c| zsh_escape_word(c)).collect();
            format!("({})", words.join(" "))
        }
        ValueHint::File(file_hint) => file_action(file_hint),
        ValueHint::Directory => "_files -/".to_string(),
    }
}

/// The plain extension-filtered glob action, with no directory
/// alternative — every non-`dirs` entry (design doc §6.1).
fn glob_action(extensions: &[String]) -> String {
    match extensions {
        [] => "_files".to_string(),
        [one] => format!("_files -g \"*.{one}\""),
        many => format!("_files -g \"*.({})\"", many.join("|")),
    }
}

/// `dirs: true` (`pmt lint`'s positional and its `--exclude`) also
/// accepts a directory as a complete answer, not just a waypoint on the
/// way to a matching file — plain `_files -g` lets you traverse through
/// directories but never offers one as the finished argument. Per the
/// design doc (§6.1), this renders as a zsh `_alternative` combining the
/// extension-filtered glob with a bare directory completion
/// (`_files -/`). The glob action is embedded as an `_alternative`
/// `tag:description:action` sub-spec, so its own double quotes are
/// escaped (`\"`) to nest inside that sub-spec's double quotes; the
/// whole thing then sits inside the OUTER single-quoted `_arguments`
/// spec line, where embedded double quotes and backslashes are literal.
fn file_action(hint: &FileHint) -> String {
    let glob = glob_action(&hint.extensions);
    if hint.dirs {
        let escaped_glob = glob.replace('"', "\\\"");
        format!("_alternative \"files:file:{escaped_glob}\" \"dirs:directory:_files -/\"")
    } else {
        glob
    }
}

fn positional_lines(positional: &Positional) -> Vec<String> {
    match positional {
        Positional::None => vec![],
        Positional::One(hint) => vec![format!(
            "'1:{}:{}'",
            positional_message(hint),
            positional_action(hint)
        )],
        Positional::OneOrMore(hint) => vec![format!(
            "'*:{}:{}'",
            positional_message(hint),
            positional_action(hint)
        )],
    }
}

fn positional_message(hint: &PositionalHint) -> &'static str {
    match hint {
        PositionalHint::File(_) => "file",
        PositionalHint::Choices(_) => "value",
        PositionalHint::Text => "pattern",
    }
}

fn positional_action(hint: &PositionalHint) -> String {
    match hint {
        PositionalHint::File(file_hint) => file_action(file_hint),
        PositionalHint::Choices(choices) => {
            // A plain `(...)` word list (unlike `_describe`) has no slot
            // for per-word descriptions, so only the literal values go
            // in here — `completions <shell>`'s only current consumer.
            let words: Vec<String> = choices.iter().map(|c| zsh_escape_word(&c.value)).collect();
            format!("({})", words.join(" "))
        }
        PositionalHint::Text => String::new(),
    }
}

/// Escape a literal word for use inside a single-quoted zsh string and
/// inside a `(...)` compadd list: colons separate `_arguments` spec
/// fields even inside parens, so any literal colon in the data itself
/// (`after:inline`) must be backslash-escaped.
fn zsh_escape_word(word: &str) -> String {
    word.replace(':', "\\:")
}

/// Same escaping as [`zsh_escape_word`] — kept as a separate name at the
/// call sites so "this is help/description text" vs "this is a literal
/// completion value" stays readable, even though today's escaping rule
/// happens to be identical.
fn zsh_escape_desc(text: &str) -> String {
    text.replace(':', "\\:")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::completions::registry::registry;

    #[test]
    fn covers_every_top_level_subcommand_and_global_flag() {
        let script = render(&registry());
        for name in [
            "compile",
            "asm",
            "link",
            "lint",
            "dis",
            "tape",
            "run",
            "ir",
            "completions",
        ] {
            assert!(
                script.contains(name),
                "missing subcommand `{name}`: {script}"
            );
        }
        assert!(script.contains("--version"));
        assert!(script.contains("--help"));
        assert!(script.contains("_pmt_tape_build"));
        assert!(script.contains("_pmt_tape_show"));
        assert!(script.contains("_pmt_ir_graph"));
    }

    #[test]
    fn emit_ir_is_equals_only_and_lists_pass_stages() {
        let script = render(&registry());
        assert!(script.contains("--emit-ir=-["), "{script}");
        // Double colon before the message: the value is OPTIONAL (a bare
        // `--emit-ir` is a real, complete flag on its own — defaults to
        // `final`). A single colon here would tell `_arguments` this
        // option always needs a value, which is wrong (man zshcompsys).
        assert!(
            script.contains("]::value:("),
            "--emit-ir's value must be optional (double colon): {script}"
        );
        assert!(script.contains("after\\:inline"), "{script}");
        assert!(script.contains("after\\:dce"), "{script}");
        assert!(script.contains("lowered"));
        assert!(script.contains("final"));
    }

    #[test]
    fn fno_expands_to_one_flag_per_pass() {
        let script = render(&registry());
        for pass in crate::optimizer::pass_names() {
            assert!(
                script.contains(&format!("--fno-{pass}[")),
                "missing --fno-{pass}: {script}"
            );
        }
    }

    #[test]
    fn extension_aware_positionals_are_glob_filtered() {
        let script = render(&registry());
        assert!(script.contains("_files -g \"*.pmc\""), "{script}"); // compile
        assert!(script.contains("_files -g \"*.pma\""), "{script}"); // asm
        assert!(script.contains("_files -g \"*.pmo\""), "{script}"); // link
        assert!(script.contains("_files -g \"*.(pmo|pmx)\""), "{script}"); // dis
        assert!(script.contains("_files -g \"*.pmx.map\""), "{script}"); // dis --map
        assert!(script.contains("_files -g \"*.pmt\""), "{script}"); // tape show / --tape-block
        assert!(script.contains("_files -g \"*.pmx\""), "{script}"); // run
        assert!(script.contains("_files -g \"*.ir.json\""), "{script}"); // ir graph
    }

    #[test]
    fn opt_level_and_tape_source_flags_are_mutually_exclusive() {
        let script = render(&registry());
        assert!(script.contains("(-O1)-O0["), "{script}");
        assert!(script.contains("(-O0)-O1["), "{script}");
        assert!(script.contains("(--tape)--tape-block["), "{script}");
        assert!(script.contains("(--tape-block)--tape["), "{script}");
    }

    #[test]
    fn dirs_true_renders_a_zsh_alternative_of_glob_and_directory() {
        let script = render(&registry());
        // `lint` and `fmt` each have a positional and an `--exclude` that
        // both accept a `.pmc` file OR a directory as a complete answer
        // (design doc §6.1) — 2 commands x 2 sites = 4 occurrences.
        let expected =
            "_alternative \"files:file:_files -g \\\"*.pmc\\\"\" \"dirs:directory:_files -/\"";
        assert!(
            script.contains(expected),
            "missing dirs-aware _alternative: {script}"
        );
        assert_eq!(
            script.matches(expected).count(),
            4,
            "expected lint's AND fmt's positional + --exclude to all render it: {script}"
        );
    }

    #[test]
    fn output_paths_are_unfiltered_files() {
        let script = render(&registry());
        // compile/asm/link/tape-build `-o` and run's --save-tape-block:
        // output paths get plain `_files`, no `-g` filter (design doc:
        // read-vs-write split).
        assert!(script.contains("-o[output path]:file:_files'"), "{script}");
    }
}
